import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./layout/NavBar";
import { ThemeProviderWrapper } from "@/components/displayThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PrDex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviderWrapper attribute="class" defaultTheme="dark">
          <NavBar>{children}</NavBar>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
